# Generated by Django 3.1.4 on 2020-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psrecord',
            name='dev_name',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
