# Generated by Django 3.1.4 on 2020-12-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0002_psrecord_dev_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Offered_price',
            new_name='offered_price',
        ),
    ]
