# Generated by Django 3.1.4 on 2020-12-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0003_auto_20201214_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('can_change_user', 'Can change user'),)},
        ),
    ]
