# Generated by Django 3.1.4 on 2020-12-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0004_auto_20201214_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterField(
            model_name='final_bid',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
