# Generated by Django 3.1.4 on 2020-12-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientegy', '0005_auto_20201214_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='sample_project_url',
        ),
    ]
